extensions:
  health_check:
    endpoint: "0.0.0.0:13134"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9317

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20
  tail_sampling:
    policies:
      - name: errors-policy
        type: status_code
        status_code: 
          status_codes: [ ERROR ]
      - name: test-policy
        type: probabilistic
        probabilistic:
          sampling_percentage: 10
  
exporters:
  logging:
    loglevel: warn
  awsxray:
    region: "eu-west-2"
  awsemf:
    region: "eu-west-2"
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray, logging]
      processors: [memory_limiter, tail_sampling]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging, awsemf]

  extensions: [health_check]

  telemetry:
    logs:
      level: warn
