extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  tail_sampling:
    policies:
      - name: errors-policy
        type: status_code
        status_code: 
          status_codes: [ ERROR ]
      - name: test-policy
        type: probabilistic
        probabilistic:
          sampling_percentage: 10

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: "eu-west-2"
  awsemf:
    region: "eu-west-2"
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray, logging]
      processors: [tail_sampling]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging, awsemf]

  extensions: [health_check, pprof]
  telemetry:
    logs:
      level: debug
