extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: "eu-west-2"
  awsemf:
    region: "eu-west-2"
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, awsemf]

  extensions: [health_check, pprof]
  telemetry:
    logs:
      level: debug
